# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      # Bind-mount the host folder → container folder
      - /data/coolify-uploads:/var/www/html/uploads
    environment:
      - UPLOAD_PATH=/var/www/html/uploads
